# Install with: brew bundle --global
tap "kristoferlund/ostt"
tap "supabase/tap"
tap "homeport/tap"

cask "gcloud-cli"
cask "font-hack-nerd-font"

brew "ack"
brew "bat"
brew "bats"
brew "coreutils"
brew "cowsay"
brew "curl"
brew "entr"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "gawk"
brew "grep"
brew "imagemagick"
# mise is deliberately absent: script/bootstrap installs it from mise.run. The
# Homebrew formula drags in llvm, which pre-Sonoma Macs must build from source.
brew "shellcheck"
brew "sqlite"
brew "terminal-notifier" # clickable macOS notifications — agent-board-hook uses it for blocked-session alerts
brew "tmux"
brew "tree"
brew "universal-ctags" # replaces the abandoned Exuberant `ctags` — parses TypeScript and reads ~/.ctags.d
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "automake"
brew "autoconf"
brew "openssl"
brew "libyaml"
brew "readline"
brew "libxslt"
brew "libtool"
brew "unixodbc"
brew "ripgrep"
brew "fzf"
brew "gh"
brew "just"
brew "overmind"
brew "lnav"
brew "jq"
brew "fd"
brew "watchexec"
brew "ffmpeg"
brew "kristoferlund/ostt/ostt"
brew "supabase"
brew "with-readline"
brew "gum"
brew "mcp-toolbox" # Google MCP Toolbox for Databases — read-only DB access for agents
