" Vim configuration.
" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.


" Plugins
" -------
filetype plugin on                " Turn on plugins.
filetype plugin indent on         " Fixes vim-endwise indent problem.
runtime macros/matchit.vim        " Load the matchit plugin.
"let g:loaded_endwise = 1
"let g:loaded_AutoClose = 1

" Navigation
" ----------
noremap <tab> <C-w><C-w>          " Use Tab to navigate between split windows 
nnoremap j gj                     " Better default nav behavior
nnoremap k gk                     " Better default nav behavior


" Markdown
" --------
set colorcolumn=100
set textwidth=100


" Prevent backup behavior
" -----------------------
set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set noswapfile
" set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location - doesnt appear to work


" Mode lines 
" ----------
" Overide OSX modelines=0; Enables modelines in files
" http://unix.stackexchange.com/q/19875/30303
set modeline
set modelines=10


" Leader key remaps
" -----------------
let mapleader = ","                            " <leader> key
map <leader>e :edit#<CR>                       " quickly switch files
nmap <silent> <leader>d :NERDTreeToggle<CR>    " Toggle the nerdtree window with leader + d (,d)


" Color shemes
" ------------
" Or use vividchalk, top-funky
" colorscheme vividchalk
" colorscheme github
colorscheme topfunky-light
" colorscheme railscasts
" colorscheme twilight
" colorscheme codeschool
" colorscheme grb256


" Command-t config
" ----------------
let g:CommandTMaxHeight=10


" Folding settings
" ----------------
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use
autocmd FileType ruby setlocal foldmethod=syntax
"autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2


" Line numbering
" ---------------
set number                        " Show line numbers.
"set relativenumber               " change line numberings for ease with writing commands


" Buffer handling 
" ---------------
nnoremap <silent> [b :bprevious <CR>
nnoremap <silent> ]b :bnext <CR>


" Rotating among results in an ack search
" ---------
map <C-n> :cn<CR>
map <C-p> :cp<CR>


" Searching
" ---------
nmap <Space> /                " Remap space bar to search
nnoremap <CR> :noh<CR><CR>    " Press enter after seach to clear highligh
nnoremap / /\v                " Default to regex search
vnoremap / /\v
set gdefault                  " don't need /g after :s or :g
set ignorecase                    " Case-insensitive searching.
set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.


" Get off my lawn - Disable the arrow keys
" ----------------------------------------
"nnoremap <Up> <nop>
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
"inoremap <Left>  <ESC>:echoe 'Exit insert mode and use a movment instead'<CR>


" Easier quitting
" ---------------
nmap <leader>q :wq!<CR>
nmap <leader>w :w!<CR>


" Splits
" ------ 
nnoremap <C-h> <C-w>h               " Move between splits
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <leader>v <C-w>v<C-w>l     " ,v to open a new vertical split and switch to it
nnoremap <leader>s <C-w>s<C-w>j     " ,s to open a new horizontal split and switch to it



" Miscellaneous 
" -------------
"let NERDTreeWinSize=16           " Make Nerd Tree smaller
nnoremap <leader>a :Ack                                       " Remap leader + a (,a) to Ack
"imap jj <ESC>                    " Map ESC to jj and save my pinky   
syntax enable                     " Turn on syntax highlighting.
set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.
"set history=50
set backspace=indent,eol,start    " Intuitive backspacing.
set hidden                        " Commands :bnext, :bprevious and :buffer won't abandon the buffer until any changes have been written
set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.
set smartcase                     " But case-sensitive if expression contains a capital letter.
set nowrap                        " Turn off line wrapping by default
set scrolloff=3                   " Show 3 lines of context around the cursor.
set title                         " Set the terminal's title
set visualbell                    " No beeping.
set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs
set laststatus=2                  " Show the status line all the time

" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

" Automatically source/reload vimrc after saving. Disabled since it doesn't
" appear to work. To reload your config manually run the command `:source ~/.vimrc`
" if has("autocmd")
"   autocmd bufwritepost .vimrc source $MYVIMRC
"   autocmd FileType ruby,eruby :let g:AutoCloseExpandEnterOn=""
" endif


call pathogen#infect()                 " Cause Tim Pope told me to add this
